spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://10.0.1.16:3306/linkage?allowMultiQueries=true
    username: linkage
    password: Zzj6p@saturn@lym

  redis:
    database: 0
    #host: 172.17.0.17
    host: 10.0.1.16
    port: 6379
    password: nKsf7IxQRUdwfj3pMLaVmRA

  mail:
    host: smtp.qq.com
    port: 465
    username: buffalo139@foxmail.com
    password: tjcybjhzpqqsbdbj
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
        debug: true

linkage:
  host: https://www.saturnluo.cn/
  #minutesToExpireSession: 10
  sessionTimeOut: 10
  RabbitMQ:
    host: '49.235.3.219'
    port: 32768
    userName: 'zzj'
    password: 'zzjHH'

logging:
  file:
    path: /home/linkage/log
