spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306
    username: root
    password: i am a fool

  redis:
      database: 0
      host: localhost
      port: 6379



