spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/linkage?allowMultiQueries=true
    username: root
    #password: '@Cmhdb_wsngp6'
    password: eikvDK5R47hK0ztHN1qL0

  redis:
    database: 0
    host: localhost
    port: 6379

linkage:
  host: 'http://localhost:8080'
  sessionTimeOut: 10
  RabbitMQ:
    host: '49.235.3.219'
    port: 32768
    userName: 'zzj'
    password: 'zzjHH'

